Add Outputting to CabanaPF Framekwork and Rework PFHub Executable
ORNL/CabanaPF pull request #16
Opened 2024-05-01 20:10 UTC by DavidJoy8

Blocked by #15 

For the below notes, I will use the following definitions: A **codeuser** is someone who uses CabanaPF to write code.  (The PFHub1a class and executable are us serving as a codeuser.)  An **enduser** is someone who .  They don't write/modify code, but use command line options (or config files if the enduser adds those).

- Added two new concepts to the framework: major_output and minor_output.  Codeusers implement these in their derived class
  - For PFHub1a, minor_output is a console print of the free energy and major output is saving the c grid
- Added an add_output function to the framework.  This tells the framework to run one of the output functions at some simulation time.  When the timestep closest to that simulation time is ran, the output function will be run as well.
  - It is not required to register them in any order.  The framework internally uses a min heap to keep track of the next output.
  - Adding output can be done partway through the run.  If outputting at that timestep would require going back in time, an exception is raised instead.
- Added a command line parser.  This lowers the amount of work codeusers need to do and provides a consistent experience to endusers.
  - There is verification that is enabled by default, but can be disabled by a codeuser if they want to do custom defaults or logic
  - 3 required arguments (if verification enabled): grid, dt, and endtime
  - 4 optional arguments: startoutput, endoutput, majoroutputs, minoroutputs
  - 2 flags: log and outputatzero
- The command line parser can add the appropriate outputs to a Runner
- The PFHub1a executable now uses the command line parser and the framework outputting.  The enduser can run their selected version (2017, 2023, or custom) with a specified number (which can be 0) of free energy and grid outputs, either log or linearlly spaced, up to a specified simulation time.

2024-05-03 15:50 UTC, streeve requested changes
This looks great - just looking to separate the test files

2024-05-03 15:50 UTC, streeve commented on unit_test/test.cpp
> +#include <CommandLine.hpp>
I think it's worth splitting these tests into a separate file (and renaming the existing test file) - maybe `CabanaPF_Test_PFHub` and `CabanaPF_Test_CommandLine`?

2024-05-03 15:53 UTC, streeve commented on src/CommandLine.hpp
> +        " --grid <grid points> --dt <timestep size> --endtime <end time> [--majoroutputs <count>] [--minoroutputs "
A longer help string would also be helpful, e.g. 
```
[--majoroutputs <count>]
    Optional frequency with which to write simulation state to file
```

2024-05-06 15:17 UTC, streeve approved these changes

2024-05-06 15:21 UTC, stvdwtt approved these changes
Looks good to me!

2024-05-06 15:22 UTC, merged